# Generated by Django 4.2.4 on 2023-09-06 11:40

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=256, unique=True, verbose_name='URL-имя'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.create_directory_path, verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступность товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(editable=False, max_length=148, unique=True, verbose_name='URL-имя'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='products.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(editable=False, max_length=70, unique=True, verbose_name='URL-имя'),
        ),
    ]
