# Generated by Django 4.2.4 on 2023-08-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=256, unique=True, verbose_name='URL-name'),
        ),
    ]
